pieceData = [
    ["Kiosk",
    "Will Westwood",
    true,"piece000.mp4",
    "This project took me too long.",
    "Digital video",
    "piece000thumb.png"], //000

    ["isolate ur self",
    "Will Westwood",
    false,"piece001.jpg",
    "Made as a sticker for a vending machine.",
    "Digital vector image at 300 ppi",
    "piece001.jpg"],  //001

    ["stay home",
    "Will Westwood",
    false,"piece002.jpg",
    "Made as a sticker for a vending machine.",
    "Digital vector image at 300 ppi",
    "piece002.jpg"],  //002

    ["Wash your hands",
    "Will Westwood",
    false,"piece003.jpg",
    "Happy birthday",
    "Digital vector image at 300 ppi",
    "piece003.jpg"],  //003

    ["teapot",
    "Steve Broughton",
    false,"piece004.jpg",
    "Teapot wot stevie B made.",
    "Fired clay scanned into digital model",
    "piece004.jpg"],  //004

    ["Unknown",
    "Could be anyone",
    false,"piece005.jpg",
    "I'm sure its lovely",
    "Made of magic dust",
    "piece005.jpg"],  //005

    ["Mind, Throat, Heart, Cage and Stranger",
    "Anastasia Avdejeva",
    false, "piece006.jpg",
    "This piece is based on my perception of myself, where I have taken all the aspects of my being that I find important and unique and have translated them through my 'internal and mental language' into a visual so that strangers will see who I am, but never be able to understand what I am.",
    "",
    "piece006.jpg"], //006

    ["Cars",
    "Danny Burchell",
    false, "piece007.jpg",
    "Photography",
    "35mm analogue film",
    "piece007.jpg"], //007

    ["Cars",
    "Danny Burchell",
    false, "piece008.jpg",
    "Photography",
    "35mm analogue film",
    "piece008.jpg"], //008

    ["Don't get distracted",
    "Suzanne Elven",
    true, "piece009.mp4",
    "'Don't get distracted' plays with the overload of information we encounter each day, and the anxiety which comes from being unable to process so much. I am responding to the role of virtual platforms in forcing so much onto us, and the space all this information takes in my personal reality. Living in a post-internet era, I'm exploring the feeling of scrolling unlimitedly through different social algorithms, floating between viral videos, warnings of human extinction, people being 'cancelled', and personalised ads. I am trying to visually express the feeling of being desensitised and overwhelmed by so much information.",
    "Film",
    "piece009thumb.jpeg"], //009

    ["Friday 13th",
    "Chelsea Jacques",
    false, "piece010.jpg",
    "Photo taken from 'Recipes For Disaster' Recipe book.",
    "",
    "piece010.jpg"], //010

    ["Playground Insults",
    "Chelsea Jacques",
    false, "piece011.jpg",
    "Photo taken from 'Recipes For Disaster' Recipe book.",
    "",
    "piece011.jpg"], //011

    ["Loser",
    "Chelsea Jacques",
    false, "piece012.JPG",
    "Photo taken from 'Recipes For Disaster' Recipe book.",
    "",
    "piece012.JPG"], //012

    ["Sunday Lunch Pudding",
    "Chelsea Jacques",
    false, "piece013.JPG",
    "Photo taken from 'Recipes For Disaster' Recipe book.",
    "",
    "piece013.JPG"], //013

    ["Verisimilitude",
    "Will Westwood",
    false, "piece014.jpg",
    "This is a realistic 3D render of a vending machine in an old bunker used as a rave in the 80s.",
    "Digital render",
    "piece014.jpg"], //014

    ["Preservation",
    "Georgia Kogel",
    false, "piece015.jpg",
    "A collection of protective nests that encase our possessions. These cocoon shaped forms intertwine the relationship between our homes and nests within nature. The idea of filling our homes with things to feel comforted and shielded was at large during the beginning of the Coronavirus pandemic, when for many, stockpiling was deemed necessary.",
    "Copper wire",
    "piece015.jpg"], //015

    ["Preservation",
    "Georgia Kogel",
    false, "piece016.jpg",
    "A collection of protective nests that encase our possessions. These cocoon shaped forms intertwine the relationship between our homes and nests within nature. The idea of filling our homes with things to feel comforted and shielded was at large during the beginning of the Coronavirus pandemic, when for many, stockpiling was deemed necessary.",
    "Copper wire and Modrock",
    "piece016.jpg"], //016

    ["Preservation",
    "Georgia Kogel",
    false, "piece017.jpg",
    "A collection of protective nests that encase our possessions. These cocoon shaped forms intertwine the relationship between our homes and nests within nature. The idea of filling our homes with things to feel comforted and shielded was at large during the beginning of the Coronavirus pandemic, when for many, stockpiling was deemed necessary.",
    "Copper wire and Modrock",
    "piece017.jpg"], //017

    ["Preservation",
    "Georgia Kogel",
    false, "piece018.jpg",
    "A collection of protective nests that encase our possessions. These cocoon shaped forms intertwine the relationship between our homes and nests within nature. The idea of filling our homes with things to feel comforted and shielded was at large during the beginning of the Coronavirus pandemic, when for many, stockpiling was deemed necessary.",
    "Copper wire and Modrock",
    "piece018.jpg"], //018





    ["title1",
    "name1",
    false,"pieceLoc1",
    "about1",
    "medium1",
    "thumb1"]  //999
];

//    title,
//    name,
//    video?, piece Location,
//    about,
//    medium.
//    thumbnail image

PDFPages = [
    "0001.jpg",
    "0002.jpg",
    "0003.jpg",
    "0004.jpg",
    "0005.jpg",
    "0006.jpg",
    "0007.jpg",
    "0008.jpg",
    "0009.jpg",
    "0010.jpg",
    "0011.jpg",
    "0012.jpg",
    "0013.jpg",
    "0014.jpg",
    "0015.jpg",
    "0016.jpg",
    "0017.jpg",
    "0018.jpg",
    "0019.jpg",
    "0020.jpg",
    "0021.jpg",
    "0022.jpg",
    "0023.jpg",
    "0024.jpg",
    "0025.jpg",
    "0026.jpg",
    "0027.jpg",
    "0028.jpg",
    "0029.jpg",
    "0030.jpg",
    "0031.jpg",
    "0032.jpg",
    "0033.jpg",
    "0034.jpg",
    "0035.jpg",
    "0036.jpg",
    "0037.jpg",
    "0038.jpg",
    "0039.jpg",
    "0040.jpg",
    "0041.jpg",
    "0042.jpg",
    "0043.jpg",
    "0044.jpg",
    "0045.jpg",
    "0046.jpg",
    "0047.jpg",
    "0048.jpg",
    "0049.jpg",
    "0050.jpg",
    "0051.jpg",
    "0052.jpg",
    "0053.jpg",
    "0054.jpg",
    "0055.jpg",
    "0056.jpg",
    "0057.jpg",
    "0058.jpg",
    "0059.jpg",
    "0060.jpg",
    "0061.jpg",
    "0062.jpg",
    "0063.jpg",
    "0064.jpg",
    "0065.jpg",
    "0066.jpg",
    "0067.jpg",
    "0068.jpg",
    "0069.jpg",
    "0070.jpg",
    "0071.jpg",
    "0072.jpg",
    "0073.jpg",
    "0074.jpg",
    "0075.jpg",
    "0076.jpg",
    "0077.jpg",
    "0078.jpg",
    "0079.jpg",
    "0080.jpg",
    "0081.jpg",
    "0082.jpg",
    "0083.jpg",
    "0084.jpg",
    "0085.jpg",
    "0086.jpg",
    "0087.jpg",
    "0088.jpg",
    "0089.jpg",
    "0090.jpg",
    "0091.jpg",
    "0092.jpg",
    "0093.jpg",
    "0094.jpg",
    "0095.jpg",
    "0096.jpg",
    "0097.jpg",
    "0098.jpg",
    "0099.jpg",
    "0100.jpg",
    "0101.jpg",
    "0102.jpg",
    "0103.jpg",
    "0104.jpg",
    "0105.jpg",
    "0106.jpg",
    "0107.jpg",
    "0108.jpg",
    "0109.jpg",
    "0110.jpg",
    "0111.jpg",
    "0112.jpg",
    "0113.jpg",
    "0114.jpg",
    "0115.jpg",
    "0116.jpg",
    "0117.jpg",
    "0118.jpg",
    "0119.jpg",
    "0120.jpg",
    "0121.jpg",
    "0122.jpg",
    "0123.jpg",
    "0124.jpg",
    "0125.jpg",
    "0126.jpg",
    "0127.jpg",
    "0128.jpg",
    "0129.jpg",
    "0130.jpg",
]